### PR TITLE
Support deprecated server.urls for CF

### PR DESCRIPTION
**Pull request by hananiel**
## Description

Need to add support for --server.url to specify the url

## Quality checklist

- [ ] Your code complies with our [Coding Style](https://github.com/SteeltoeOSS/.github/blob/main/contributing-docs/contributing-code-style.md).
- [ ] You've updated unit and/or integration tests for your change, where applicable.
- [ ] You've updated documentation for your change, where applicable.
      If your change affects other repositories, such as [Documentation](https://github.com/SteeltoeOSS/Documentation), [Samples](https://github.com/SteeltoeOSS/Samples) and/or [MainSite](https://github.com/SteeltoeOSS/MainSite), add linked PRs here.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.
- [ ] You've added required license files and/or file headers (explaining where the code came from with proper attribution), where code is copied from StackOverflow, a blog, or OSS.

### CODE REVIEW

**Comment by hananiel** [comment]
> SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=SteeltoeOSS_steeltoe&pullRequest=1080)
> 
> [Bug](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=SteeltoeOSS_steeltoe&pullRequest=1080&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=SteeltoeOSS_steeltoe&pullRequest=1080&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=SteeltoeOSS_steeltoe&pullRequest=1080&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=SteeltoeOSS_steeltoe&pullRequest=1080&metric=new_duplicated_lines_density&view=list)



> SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=SteeltoeOSS_steeltoe&pullRequest=1080)
> 
> [Bug](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=SteeltoeOSS_steeltoe&pullRequest=1080&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=SteeltoeOSS_steeltoe&pullRequest=1080&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=SteeltoeOSS_steeltoe&pullRequest=1080&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=SteeltoeOSS_steeltoe&pullRequest=1080&metric=new_duplicated_lines_density&view=list)

I do not think this is correct - running locally I get this: 
image

**Review by dtillman — APPROVED** [review]

**Comment by TimHess** [comment]
> > SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=SteeltoeOSS_steeltoe&pullRequest=1080)
> > [Bug](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=CODE_SMELL)
> > [](https://sonarcloud.io/component_measures?id=SteeltoeOSS_steeltoe&pullRequest=1080&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=SteeltoeOSS_steeltoe&pullRequest=1080&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=SteeltoeOSS_steeltoe&pullRequest=1080&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=SteeltoeOSS_steeltoe&pullRequest=1080&metric=new_duplicated_lines_density&view=list)
> 
> > SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=SteeltoeOSS_steeltoe&pullRequest=1080)
> > [Bug](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=SteeltoeOSS_steeltoe&pullRequest=1080&resolved=false&types=CODE_SMELL)
> > [](https://sonarcloud.io/component_measures?id=SteeltoeOSS_steeltoe&pullRequest=1080&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=SteeltoeOSS_steeltoe&pullRequest=1080&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=SteeltoeOSS_steeltoe&pullRequest=1080&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=SteeltoeOSS_steeltoe&pullRequest=1080&metric=new_duplicated_lines_density&view=list)
> 
> I do not think this is correct - running locally I get this: image

You're right, something is broken with Sonar Cloud's code coverage report in this branch (seems `release/3.2` is working fine) - should be OK to ignore that check for right now

**Review by TimHess — APPROVED** [review]

**Pull request merged**
