### PR TITLE
Get ConfigServer PollingInterval from Configuration object

### PR DESCRIPTION
**Pull request by hermogenes**
This PR update settings for PollingInterval from IConfiguration object allowing us configure it using appsettings instead of initialize it via default settings.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/SteeltoeOSS/Steeltoe?pullRequest=853) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/SteeltoeOSS/Steeltoe?pullRequest=853) before we can accept your contribution.<br/><br/>:x: hermogenes [sign now](https://cla.dotnetfoundation.org/SteeltoeOSS/Steeltoe?pullRequest=853)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/SteeltoeOSS/Steeltoe?pullRequest=853) it.</sub>

**Comment by TimHess** [comment]
I don't currently know why, but this test failed on the Linux build `Steeltoe.Extensions.Configuration.ConfigServer.Test.ConfigServerConfigurationProviderTest.Create_WithPollingTimer`.

The build is re-running now in case it was a fluke, but we'll need it to make sure it passes before this PR can merge. If it fails again I'll look at it next week (if nobody else gets to it first)

**Review by TimHess — APPROVED** [review]
LGTM, thanks!

**Comment by hermogenes** [comment]
I didn't get why the test is failing. I'm investigating

**Review by dtillman — DISMISSED** [review]
LGTM

**Pull request merged**
