### PR TITLE
Allow eureka repeat register and unregister

### PR DESCRIPTION
**Pull request by pengweiqhca**

### CODE REVIEW

**Comment by TimHess** [comment]
@pengweiqhca is this so that you can take an app (instance) offline or online on-demand, perhaps like what #131 is describing?

**Comment by pengweiqhca** [comment]
> @pengweiqhca is this so that you can take an app (instance) offline or online on-demand, perhaps like what #131 is describing?

Yes, but we has implemented. 
``` C#
public class TuhuEurekaDiscoveryClient : EurekaDiscoveryClient
{
	public Task StartupAsync()
	{
		if (_shutdown == 0) return Task.CompletedTask;

		_appInfoManager.InstanceStatus = InstanceStatus.UP;

		return InitializeAsync().ContinueWith(_ => _shutdown = 0);
	}
}
```
I want make `StartupAsync()` is simpler. So, have this PR

**Comment by TimHess** [comment]
I did [some preliminary work](https://github.com/SteeltoeOSS/Steeltoe/compare/registry_endpoint) in this area already - would it be cleaner to discretely change the status, or are you really wanting to start and stop the client?

**Comment by pengweiqhca** [comment]
Yes, if don't stop, _heartBeatTimer will modify the status of the client

**Comment by TimHess** [comment]
@pengweiqhca does it look like the work I started will work for you? I didn't have a chance to work on it today, but the intent is that heartbeats will continue to fire (but without changing the status back to up)

**Pull request closed without merging**
