### PR TITLE
Minor Eureka enhancements and Fix ApplicationInstanceInfo binding

### PR DESCRIPTION
**Pull request by TimHess**
For Eureka:
- Better handling of empty `OK` response from heartbeat request
- Allow use of app addresses from "urls" in configuration
- Use secure port in app id if enabled

Port-related issues in Tye (Env variable `PORT` might be a semicolon delimited string) turned out to be related to bare/default `ApplicationInstanceInfo`  binding to the root of configuration instead of a base path. The last commit in this PR adds a new constructor that will result in binding `ApplicationInstanceInfo` to keys under `application` instead of the root

### CODE REVIEW

**Comment by cecilphillip** [comment]
I've been staring at this code for hours trying to figure out why I was getting `System.InvalidOperationException: Failed to convert configuration value at 'Port' to type 'System.Int32'.` with Tye. Guess I'll wait til this fix gets pushed.

**Comment by ddieruf** [comment]
@cecilphillip this was sparked from using tye in this proj - https://github.com/spboyer/steeltoe-sample.

**Comment by TimHess** [comment]
@cecilphillip sorry about that, it made a pretty crappy experience. A short-term workaround to use Steeltoe in Tye is to specify that only http or https should be used so that you don't get two ports stuffed into a variable where only one port was previously expected:
```
services:
- name: musicstoreservice
  project: src/MusicStoreService/MusicStoreService.csproj
  bindings:
    - protocol: http
```

**Comment by cecilphillip** [comment]
@ddieruf nice. I have a sample [here](https://github.com/cecilphillip/ContosoCrafts/tree/steeltoe) that I'm trying to add Tye support to.

@TimHess Thanks! I'll try that binding setting

**Review by dtillman — APPROVED** [review]

**Pull request merged**
