### PR TITLE
Review ConfigServer log levels

### LINKED ISSUE #1316: Config server URLs appear encoded in logs
## Describe the bug
The following appears in logs
```
info: Steeltoe.Configuration.ConfigServer.ConfigServerConfigurationProvider[0]
      Fetching configuration from server at: http://127.0.0.1:8888            
info: Steeltoe.Configuration.ConfigServer.ConfigServerConfigurationProvider[0]      
      Config Server returned status: OK invoking path: http%3A%2F%2F127.0.0.1%3A8888
info: Steeltoe.Configuration.ConfigServer.ConfigServerConfigurationProvider[0]                                    
      Located environment name: cpdemo-blue, profiles: Development, labels: (null), version: (null), state: (null)
``` 

Those URLs look encoded

## Steps to reproduce 
1. Add config server using `WebApplicationBuilder` like so `builder.AddConfigServer();`

## Expected behavior
Urls to appear non-url encoded

## Environment (please complete the following information):
 - Steeltoe Version: 4.0.323-alpha
 - Platform: Local
 - OS: Windows
 - .NET Version: 8

### PR DESCRIPTION
**Pull request by TimHess**
## Description

Fixes #1316 

## Quality checklist

- [ ] Your code complies with our [Coding Style](https://github.com/SteeltoeOSS/.github/blob/main/contributing-docs/contributing-code-style.md).
- [ ] You've updated unit and/or integration tests for your change, where applicable.
- [ ] You've updated documentation for your change, where applicable.
      If your change affects other repositories, such as [Documentation](https://github.com/SteeltoeOSS/Documentation), [Samples](https://github.com/SteeltoeOSS/Samples) and/or [MainSite](https://github.com/SteeltoeOSS/MainSite), add linked PRs here.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.
- [ ] You've added required license files and/or file headers (explaining where the code came from with proper attribution), where code is copied from StackOverflow, a blog, or OSS.

### CODE REVIEW

**Review by bart-vmware — COMMENTED** [review]
I suspect that the URI escaping was fixed recently, can you confirm?

Also, running the integration test `SpringCloudConfigServer_DiscoveryFirst_ReturnsExpectedDefaultData` is broken, please add a project reference to `Steeltoe.Discovery.Eureka` from project `Steeltoe.Configuration.ConfigServer.Integration.Test` to fix that.

Other than that, LGTM.

**Comment by TimHess** [comment]
> I suspect that the URI escaping was fixed recently, can you confirm?
> 
> Also, running the integration test `SpringCloudConfigServer_DiscoveryFirst_ReturnsExpectedDefaultData` is broken, please add a project reference to `Steeltoe.Discovery.Eureka` from project `Steeltoe.Configuration.ConfigServer.Integration.Test` to fix that.
> 
> Other than that, LGTM.

Yes, the URI escaping was already fixed. Ref has been added

**Review by bart-vmware — APPROVED** [review]

**Pull request merged**
