### PR TITLE
Reduce the number of direct constructor callers to management endpoint base

### PR DESCRIPTION
**Pull request by kimbell**
This is another step on the journey to refactoring the management endpoint code. 
It contains a lot of changes, but they are similar for each endpoint. 

- A public interface is added for each endpoint
- Interface can be used for public consumption so that we can make classes internal in the future. 
- Service collection contains entry that maps interface to actual implementation

At some point we can mark code as obsolete to trigger consumers to move over to interface. 
MetricsEndpoint is using some protected internal code that prevented some code from using an interface.

In the test project I've created a `TestContext` class that contains the state for each test. This adds Options and Logging infrastructure. Tests are  now using `IServiceProvider `to create endpoint rather than using the constructor directly.

Tests that log information is now available in the XUnit output.

> Unable to access the Dynamic Logging provider, log configuration unavailable
> Health check requested for a group that is not configured

related to #545

### CODE REVIEW

**Review by TimHess — COMMENTED** [review]
Looks fine to me - we can merge after conflicts are resolved, unless @hananiel has any thoughts

**Review by dtillman — COMMENTED** [review]
LGTM

**Review by TimHess — APPROVED** [review]

**Pull request merged**
