### PR TITLE
add .NET 7 target for tests

### LINKED ISSUE #1034: Steeltoe tests should be run on .NET 7
.NET 7 has reached RC2, we need to add it to the tests as a target framework to ensure compatibility

### PR DESCRIPTION
**Pull request by TimHess**
## Description

Adds .NET 7 as a target framework for all unit tests, updates component tests and Steeltoe.All to also run tests against .NET 7 

Fixes #1034

## Quality checklist

- [x] Your code complies with our [Coding Style](https://github.com/SteeltoeOSS/.github/blob/main/contributing-docs/contributing-code-style.md).
- [x] You've updated unit and/or integration tests for your change, where applicable.
- [ ] You've updated documentation for your change, where applicable.
      If your change affects other repositories, such as [Documentation](https://github.com/SteeltoeOSS/Documentation), [Samples](https://github.com/SteeltoeOSS/Samples) and/or [MainSite](https://github.com/SteeltoeOSS/MainSite), add linked PRs here.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.
- [x] You've added required license files and/or file headers (explaining where the code came from with proper attribution), where code is copied from StackOverflow, a blog, or OSS.

### CODE REVIEW

**Comment by bart-vmware** [comment]
Can you try passing `--jb --dotnetcoresdk=7.0.100-rc.2.22477.23` to the `regitlint` invocations in `verify-code-style.yml` to fix the cibuild?

**Comment by TimHess** [comment]
This should have been marked as a draft earlier... I'm not sure we want to merge this right away as it could require project work to be done from a preview edition of Visual Studio. I'm open to thoughts/opinions on when to merge it, but I'm not in a rush to merge and think it would be reasonable to bring updates from `main` into this branch for a while

**Review by hananiel — APPROVED** [review]
LGTM;

**Comment by TimHess** [comment]
At this point, this PR is stale. Given there were no issues found on .NET 7, we can be looking at .NET 8 instead anyway

**Pull request closed without merging**
