### PR TITLE
Automated code cleanup

### PR DESCRIPTION
**Pull request by bart-vmware**
## Description

This PR contains the result of automated code cleanup, using the tools added in #965.

## Quality checklist

- [x] Your code complies with our [Coding Style](https://github.com/SteeltoeOSS/.github/blob/main/contributing-docs/contributing-code-style.md).
- [ ] You've updated unit and/or integration tests for your change, where applicable.
- [ ] You've updated documentation for your change, where applicable.
      If your change affects other repositories, such as [Documentation](https://github.com/SteeltoeOSS/Documentation), [Samples](https://github.com/SteeltoeOSS/Samples) and/or [MainSite](https://github.com/SteeltoeOSS/MainSite), add linked PRs here.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.
- [ ] You've added required license files and/or file headers (explaining where the code came from with proper attribution), where code is copied from StackOverflow, a blog, or OSS.

### CODE REVIEW

**Comment by bart-vmware** [comment]
To reviewers: VerifyCodeStyle failing with timeout is because it runs in diff-mode (therefore batching multiple calls), while the diff is enormous. This wouldn't occur normally, so I think we can ignore it here.

**Review by TimHess — APPROVED** [review]
looks fine to me, we may need to revisit some of the rules as we experience them

**Pull request merged**
