### PR TITLE
Enable code analysis rules S138, S2931

### LINKED ISSUE #922: Address S138: Functions should not have too many lines of code
Address existing violations of [S138: Functions should not have too many lines of code](https://rules.sonarsource.com/csharp/RSPEC-138) in the codebase and set severity to `Warning` in `Steeltoe.Debug.ruleset` and `Steeltoe.Release.ruleset`.

To find existing violations, enable the rule (see above) and rebuild `src/Steeltoe.All.sln` to make them appear in the Output window.

To address the violations, choose from the following on a case-by-case basis:
- Fix the violation by changing the code to not violate the rule (usually extract method)
- Suppress the violation in code using `#pragma warning disable/restore`, preceded by a justification comment if not obvious

To be decided: the guideline that tests should contain everything relevant to understand the test supersedes this rule, so we may want to turn off this rule for test projects (using `NoWarn` in `sharedtest.props`).

### LINKED ISSUE #932: Address S2931: Classes with "IDisposable" members should implement "IDisposable"
Address existing violations of [S2931: Classes with "IDisposable" members should implement "IDisposable"](https://rules.sonarsource.com/csharp/RSPEC-2931) in the codebase and set severity to `Warning` in `Steeltoe.Debug.ruleset` and `Steeltoe.Release.ruleset`.

To find existing violations, enable the rule (see above) and rebuild `src/Steeltoe.All.sln` to make them appear in the Output window.

To address the violations, choose from the following on a case-by-case basis:
- Fix the violation by changing the code to not violate the rule
- Suppress the violation in code using `#pragma warning disable/restore`, preceded by a justification comment if not obvious

### PR DESCRIPTION
**Pull request by thompson-tomo**
## Description

This will enable the following analysis rules without any code changes:

New rules enabled
- S138
- S2931

## Quality checklist

- [x] Your code complies with our [Coding Style](https://github.com/SteeltoeOSS/.github/blob/main/contributing-docs/contributing-code-style.md).
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Fixes #922 
Fixes #932

### CODE REVIEW

**Review by bart-vmware — APPROVED** [review]
Thanks. The issues for the additional rules can't be closed yet. They are currently turned off for all projects that haven't yet undergone API review (see https://github.com/SteeltoeOSS/Steeltoe/blob/main/shared-package.props#L65). That doesn't apply to S2699, whose issue lists additional work, and we haven't yet decided if/how to approach that.

**Comment by bart-vmware** [comment]
Can you please update the PR description with "closes"/"fixes" so these two issues get auto-resolved on merge?

**Comment by bart-vmware** [comment]
I meant to add this at the bottom of the description:
```
Fixes #922
Fixes #932
```
which would update:
image

See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue.

**Comment by thompson-tomo** [comment]
Thanks for the link @bart-vmware changes made as requested.

**Pull request merged**
