### PR TITLE
Update RabbitListenerDeclareAtrributeProcessor.cs

### PR DESCRIPTION
**Pull request by wainwrightmark**
RabbitListenerDeclareAtrributeProcessor now creates a TopicExchange instead of a FanoutExchange when `type == ExchangeType.TOPIC`

Resolves https://github.com/SteeltoeOSS/Steeltoe/issues/696

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/SteeltoeOSS/Steeltoe?pullRequest=697) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/SteeltoeOSS/Steeltoe?pullRequest=697) before we can accept your contribution.<br/><br/>:x: wainwrightmark [sign now](https://cla.dotnetfoundation.org/SteeltoeOSS/Steeltoe?pullRequest=697)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/SteeltoeOSS/Steeltoe?pullRequest=697) it.</sub>

**Review by hananiel — APPROVED** [review]
LGTM.

**Review by hananiel — APPROVED** [review]

**Pull request merged**
