### PR TITLE
Fix addresses

### LINKED ISSUE #537: DetermineAddresses never returns a empty or null value
## Describe the bug
The `DetermineAddresses()` method always returns a value. Because of this the calling method `SetAddresses()` will always try to set an address. This forces the use of `AmqpTcpEndpoint` to connect to RabbitMQ during the `IConnectionFactory` connection calls. Rather than the service name connection.

## Steps to reproduce 
1. Configure `RabbitOptions` without setting the `addresses` property.
2. Run App

## Expected behavior
Library should not set addresses if not configured. 

## Environment (please complete the following information):
 - Steeltoe Version: 3.0.1
 - Platform: Tanzu/PCF
 - OS: Windows
 - .NET Version: 3.1

### PR DESCRIPTION
**Pull request by TravisBoatman**
This fixes #537

### CODE REVIEW

**Review by dtillman — COMMENTED** [review]
Would it not be enough to just make the change to RabbitOptions (i.e. return null) and leave the rest the same?

**Comment by dtillman** [comment]
@TravisBoatman : Any thoughts ?

**Comment by TravisBoatman** [comment]
Good catch. Yes, you could just include the RabbitOption changes and leave everything else.

**Comment by jkonicki** [comment]
Closing in favor of #552

**Pull request closed without merging**
