### PR TITLE
Remove obsolete types and members

### PR DESCRIPTION
**Pull request by bart-vmware**
## Description

This PR removes types and members marked as `[Obsolete]` from the codebase.

Addresses part of #964.

## Quality checklist

- [x] Your code complies with our [Coding Style](https://github.com/SteeltoeOSS/.github/blob/main/contributing-docs/contributing-code-style.md).
- [x] You've updated unit and/or integration tests for your change, where applicable.
- [ ] You've updated documentation for your change, where applicable.
      If your change affects other repositories, such as [Documentation](https://github.com/SteeltoeOSS/Documentation), [Samples](https://github.com/SteeltoeOSS/Samples) and/or [MainSite](https://github.com/SteeltoeOSS/MainSite), add linked PRs here.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.
- [ ] You've added required license files and/or file headers (explaining where the code came from with proper attribution), where code is copied from StackOverflow, a blog, or OSS.

### CODE REVIEW

**Comment by bart-vmware** [comment]
The method `Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider.Build` is still marked as obsolete, because it has several usages and I don't understand what to replace them with:

```c#
[Obsolete("Will be removed in next release, use the ConfigServerConfigurationSource")]
public virtual IConfigurationProvider Build(IConfigurationBuilder builder)
```

Please advice on how to remove this one and update usages.

**Comment by TimHess** [comment]
> The method `Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider.Build` is still marked as obsolete, because it has several usages and I don't understand what to replace them with:
> 
> ```cs
> [Obsolete("Will be removed in next release, use the ConfigServerConfigurationSource")]
> public virtual IConfigurationProvider Build(IConfigurationBuilder builder)
> ```
> 
> Please advice on how to remove this one and update its usages.

Removing `, IConfigurationSource` on line 29 clears the only compilation issue I'm seeing, what else breaks?

**Comment by bart-vmware** [comment]
> > The method `Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider.Build` is still marked as obsolete, because it has several usages and I don't understand what to replace them with:
> > ```cs
> > [Obsolete("Will be removed in next release, use the ConfigServerConfigurationSource")]
> > public virtual IConfigurationProvider Build(IConfigurationBuilder builder)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please advice on how to remove this one and update its usages.
> 
> Removing `, IConfigurationSource` on line 29 clears the only compilation issue I'm seeing, what else breaks?

I searched for usages of the `Build` method, which apparently showed me all usages from the interface method. Removing the interface and the method doesn't fail the build. Thanks for the help.

**Review by TimHess — DISMISSED** [review]
LGTM

**Review by TimHess — APPROVED** [review]

**Pull request merged**
