### PR TITLE
.Wait() => .GetAwaiter().GetResult()

### PR DESCRIPTION
**Pull request by pengweiqhca**

### CODE REVIEW

**Comment by TimHess** [comment]
Thanks!

**Comment by TimHess** [comment]
@pengweiqhca  I'm sorry, but it looks like we were missing the .NET Foundation CLA bot when this PR was entered, can you confirm that you've signed the CLA? - https://cla.dotnetfoundation.org/SteeltoeOSS/steeltoe?pullRequest=75

**Comment by pengweiqhca** [comment]
I has signed
> You have signed the CLA for multiple repositories or organizations
> Version: 2017-08-31

**Comment by TimHess** [comment]
Thanks again!

**Pull request merged**
