### PR TITLE
Add initial k8s service discovery

### PR DESCRIPTION
**Pull request by tscrypter**
- Add KuberenetesDiscoveryClient
- If `spring:cloud:kubernetes:discovery` is configured, `services.AddDiscoveryClient(Configuration);` will add a KubernetesDiscoveryClient

#107

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/SteeltoeOSS/Steeltoe?pullRequest=374) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/SteeltoeOSS/Steeltoe?pullRequest=374) before we can accept your contribution.<br/><br/>:x: tscrypter [sign now](https://cla.dotnetfoundation.org/SteeltoeOSS/Steeltoe?pullRequest=374)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/SteeltoeOSS/Steeltoe?pullRequest=374) it.</sub>

**Comment by TimHess** [comment]
Hey, sorry I haven't looked at this yet, I am fully expecting to spend time with it tomorrow! 

Changes from this PR and #378 will need to merge with each other very soon, so as you're looking at this space your thoughts on that PR might be interesting as well if you're interested in taking a look.

**Comment by tscrypter** [comment]
No problem, I got pulled back into some work. I am planning on finishing resolving my config error and will try to resolve the failed checks.

**Comment by TimHess** [comment]
The code generally looks good and I had at least partial success using it, but I had local environment issues trying to test it out today (likely not related) so I can't say I've completely tested through it all yet

**Comment by tscrypter** [comment]
The specific issue I'm still working through is setting kubernetes discovery options via appsettings. When attempting to override the namespace, the values for the options are the class defaults.

**Pull request merged**
